### ISSUE TITLE
Only predict the Home team no matter what

### ISSUE THREAD

**Issue by SamuelLachance** [pramodkondur/NHL-Betting-Predictor-AWS-Flask-Docker-CI-CD#1]
title

**Comment by pramodkondur** [comment]
Issue fixed. Thanks for bringing it up. Attached an image away team prediction as well. 
**Responsible Betting:** Please remember that sports betting should be done responsibly. Always gamble within your means and be aware of the risks involved. Betting outcomes can be unpredictable, and it's crucial to manage your bankroll wisely. If you feel that your gambling habits are becoming problematic, consider seeking assistance from a professional or a support group.
